/**
 * STEEL Assessment Data Types
 * 
 * These types match the data structure generated by the STEEL assessment
 * HTML application and used throughout the React dashboard integration.
 */

export type SteelRiskLevel = 'LOW' | 'MODERATE' | 'ELEVATED' | 'HIGH';

export type SteelPriority = 'CRITICAL' | 'HIGH' | 'MODERATE' | 'LOW';

export type SteelFactor = 'political' | 'economic' | 'social' | 'technological' | 'environmental' | 'legal';

export interface FactorScores {
  political: number;
  economic: number;
  social: number;
  technological: number;
  environmental: number;
  legal: number;
}

export interface SteelInsight {
  factor: SteelFactor;
  text: string;
  priority?: SteelPriority;
}

export interface SteelRecommendation {
  factor: SteelFactor;
  factorName: string;
  score: number;
  priority: SteelPriority;
  timeline: string;
  actions: string[];
  quickWins: string[];
  longTerm: string[];
}

export interface SteelInsights {
  executiveSummary: string;
  keyInsights: SteelInsight[];
  strengths: SteelInsight[];
  opportunities: SteelInsight[];
  riskContext: string;
}

export interface SteelAssessmentData {
  factorScores: FactorScores;
  composite: number;
  timestamp: string;
  insights?: SteelInsights;
  recommendations?: SteelRecommendation[];
}

export interface SteelAssessmentStorage {
  [key: string]: string; // Question answers stored as q1, q2, etc.
}

